In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("Travel.csv")

In [4]:
df.head()

CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0      200000          1  41.0     Self Enquiry         3              6.0   
1      200001          0  49.0  Company Invited         1             14.0   
2      200002          1  37.0     Self Enquiry         1              8.0   
3      200003          0  33.0  Company Invited         1              9.0   
4      200004          0   NaN     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0        Salaried  Female                       3                3.0   
1        Salaried    Male                       3                4.0   
2     Free Lancer    Male                       3                4.0   
3        Salaried  Female                       2                3.0   
4  Small Business    Male                       2                3.0   

  ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0         Deluxe                    3.0        Single            1.0   
1         Deluxe                    4.0      Divorced            2.0   
2          Basic                    3.0        Single            7.0   
3          Basic                    3.0      Divorced            2.0   
4          Basic                    4.0      Divorced            1.0   

   Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0         1                       2       1                       0.0   
1         0                       3       1                       2.0   
2         1                       3       0                       0.0   
3         1                       5       1                       1.0   
4         0                       5       1                       0.0   

  Designation  MonthlyIncome  
0     Manager        20993.0  
1     Manager        20130.0  
2   Executive        17090.0  
3   Executive        17909.0  
4   Executive        18468.0

In [5]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [6]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   CustomerID                4888 non-null   int64  
 1   ProdTaken                 4888 non-null   int64  
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object 
 4   CityTier                  4888 non-null   int64  
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object 
 7   Gender                    4888 non-null   object 
 8   NumberOfPersonVisiting    4888 non-null   int64  
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object 
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object 
 13  NumberOfTrips             4748 non-null   float64
 14  Passport

In [7]:
df["TypeofContact"].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

In [8]:
df["Occupation"].value_counts()

Occupation
Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: count, dtype: int64

In [9]:
df["Gender"].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [10]:
df["Gender"] = df["Gender"].replace("Fe Male", "Female")

In [11]:
df["Gender"].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [12]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [13]:
df["MaritalStatus"]=df["MaritalStatus"].replace("Single", "Unmarried")

In [14]:
df["MaritalStatus"].value_counts()

MaritalStatus
Married      2340
Unmarried    1598
Divorced      950
Name: count, dtype: int64

In [15]:
df["Designation"].value_counts()

Designation
Executive         1842
Manager           1732
Senior Manager     742
AVP                342
VP                 230
Name: count, dtype: int64

In [16]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [17]:
medianAge=df["Age"].median()
df["Age"]=df["Age"].fillna(medianAge)

In [18]:
modeToc = df["TypeofContact"].mode()[0]
df["TypeofContact"]=df["TypeofContact"].fillna(modeToc)


In [19]:
df["DurationOfPitch"]=df["DurationOfPitch"].fillna(df["DurationOfPitch"].median())

In [20]:
df["NumberOfFollowups"]=df["NumberOfFollowups"].fillna(df["NumberOfFollowups"].median())

In [21]:
df["PreferredPropertyStar"]=df["PreferredPropertyStar"].fillna(df["PreferredPropertyStar"].median())

In [22]:
df["NumberOfTrips"]=df["NumberOfTrips"].fillna(df["NumberOfTrips"].median())

In [23]:
df["NumberOfChildrenVisiting"]=df["NumberOfChildrenVisiting"].fillna(df["NumberOfChildrenVisiting"].median())

In [24]:
df["MonthlyIncome"]=df["MonthlyIncome"].fillna(df["MonthlyIncome"].median())

In [25]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

In [26]:
df.drop("CustomerID",inplace=True,axis=1)

In [27]:
df["Totalvisit"]=df["NumberOfPersonVisiting"]+df["NumberOfChildrenVisiting"]

In [28]:
df.drop(columns=['NumberOfPersonVisiting','NumberOfChildrenVisiting'],inplace=True,axis=1)

In [29]:
df.head()

ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0          1  41.0     Self Enquiry         3              6.0   
1          0  49.0  Company Invited         1             14.0   
2          1  37.0     Self Enquiry         1              8.0   
3          0  33.0  Company Invited         1              9.0   
4          0  36.0     Self Enquiry         1              8.0   

       Occupation  Gender  NumberOfFollowups ProductPitched  \
0        Salaried  Female                3.0         Deluxe   
1        Salaried    Male                4.0         Deluxe   
2     Free Lancer    Male                4.0          Basic   
3        Salaried  Female                3.0          Basic   
4  Small Business    Male                3.0          Basic   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0     Unmarried            1.0         1   
1                    4.0      Divorced            2.0         0   
2                    3.0     Unmarried            7.0         1   
3                    3.0      Divorced            2.0         1   
4                    4.0      Divorced            1.0         0   

   PitchSatisfactionScore  OwnCar Designation  MonthlyIncome  Totalvisit  
0                       2       1     Manager        20993.0         3.0  
1                       3       1     Manager        20130.0         5.0  
2                       3       0   Executive        17090.0         3.0  
3                       5       1   Executive        17909.0         3.0  
4                       5       1   Executive        18468.0         2.0

In [30]:
X=df.drop(["ProdTaken"],axis=1)

In [31]:
Y=df["ProdTaken"]

In [32]:
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [33]:
catogorical_feat=X.select_dtypes(include="object").columns

In [34]:
numeric_feat=X.select_dtypes(exclude="object").columns

In [35]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

In [36]:
StandardScaler=StandardScaler()
OneHotEncoder=OneHotEncoder(drop="first")

In [37]:
preprocess=ColumnTransformer([
    ("OneHotEncoder",OneHotEncoder,catogorical_feat),
    ("StandardScaler",StandardScaler,numeric_feat)
])

In [38]:
X_train=preprocess.fit_transform(X_train)

In [39]:
X_test=preprocess.transform(X_test)

In [54]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [58]:
%pip install xgboost

   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/56.8 MB ? eta -:--:--
   ---------------------------------------- 0.5/56.8 MB 1.1 MB/s eta 0:00:51
    --------------------------------------- 0.8/56.8 MB 1.2 MB/s eta 0:00:47
    --------------------------------------- 1.0/56.8 MB 1.3 MB/s eta 0:00:43
    --------------------------------------- 1.3/56.8 MB 1.3 MB/s eta 0:00:44
   - -------------------------------------- 1.6/56.8 MB 1.3 MB/s eta 0:00:45
   - -------------------------------------- 1.6/56.8 MB 1.3 MB/s eta 0:00:45
   - -------------------------------------- 1.6/56.8 MB 1.3 MB/s eta 0:00:45
   - -------------------------------------- 1.8/56.8 MB 853.4 kB/s eta 0:01:05
   - -------------------------------------- 1.8/56.8 MB 853.4 kB/s eta 0:01:05
   - -------------------------------------- 2.1/56.8 MB 804.5 kB/s eta 0:01:09
   - ---------

In [59]:
from xgboost import XGBClassifier

In [60]:
models={
    "random forest":RandomForestClassifier(),
    "adaboost":AdaBoostClassifier(),
    "gradient boost":GradientBoostingClassifier(),
    "xgboost": XGBClassifier()
}

In [61]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    a_s=accuracy_score(Y_test,Y_pred)
    c_m=confusion_matrix(Y_test,Y_pred)
    c_r=classification_report(Y_test,Y_pred)
    print(list(models.keys())[i])
    print(a_s)
    print(c_m)
    print("="*30)
    print(c_r)
    print("="*30)

random forest
0.9202453987730062
[[783   4]
 [ 74 117]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95       787
           1       0.97      0.61      0.75       191

    accuracy                           0.92       978
   macro avg       0.94      0.80      0.85       978
weighted avg       0.92      0.92      0.91       978

adaboost
0.8353783231083844
[[772  15]
 [146  45]]
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       787
           1       0.75      0.24      0.36       191

    accuracy                           0.84       978
   macro avg       0.80      0.61      0.63       978
weighted avg       0.82      0.84      0.80       978

gradient boost
0.8588957055214724
[[765  22]
 [116  75]]
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       787
           1       0.77      0.39      0.52       191

    accuracy      